### ISSUE TITLE
Confirming User Action views in between various steps of the checkout process

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#11]
I am seeing Confirming User Action views in between various steps of the checkout process.
I suppose that is because we are not using csrf authenticators in the url?

**Comment by davisagli** [comment]
Yes - but the right fix depends on whether the db writes are intentional or not. Can you be more specific about how to reproduce them?

David Glick
(mobile)

**Comment by witekdev** [comment]
Sorry @davisagli I cleared my browser cache and I no longer see this. must have been some left over cached code.

**Comment by davisagli** [comment]
Then maybe it's some data structure that was getting initialized the first time you made a purchase. We can try to reproduce it in a fresh Plone site or with a new user.

David Glick
(mobile)

**Comment by witekdev** [comment]
ok, reopening..

**Comment by davisagli** [comment]
Tried to reproduce in a new site but couldn't.
