### ISSUE TITLE
Edit Shipping Method UX improvement

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#12]
When editing a shipping option, the user only has the option to save or delete.
Clicking outside of the popup/modal does not close it, so if the user wants to cancel the operation, they have to explicitly click the 'X'. I think it would be good to improve the Ui/UX on this form. Perhaps adding a cancel button or allowing a click outside of the modal to close the modal and 'cancel the operation'

**Comment by davisagli** [comment]
I'm fine with that, but doesn't seem like a blocker especially since this is an admin-only UI. We're using the modal from `mockup`; it might have a setting for closing when you click outside the modal.

**Comment by witekdev** [comment]
added a Cancel button, couldn't figure out how to add a parameter to close with clicked outside of modal. It's not something that is documented: http://plone.github.io/mockup/dev/#pattern/modal
