### ISSUE TITLE
Book Images

### ISSUE THREAD

**Issue by SDHSPress** [jazkarta/jazkarta.shop#18]
Even if there is a book image under the book's folder, I cannot update the book info without uploading a new image from my computer. How do I get the book from the folder to be recognized as the cover image?

**Comment by witekdev** [comment]
@SDHSPress I think it would be better for you to file these issues under https://github.com/jazkarta/sdhsp-buildout
The issues listed here are related more to the technical aspects of the jazkarta.shop product

**Comment by SDHSPress** [comment]
Whoops, didn't realize that I wasn't under the sdhsp-buildout. Sorry
