### ISSUE TITLE
Sync quantities and items with "my cart" while in the review-cart view

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#20]
If we modify the items and/or quantities in the review-cart view, we should be dynamically updating the "My Cart" details as well.

**Comment by davisagli** [comment]
Or just don't show "My Cart" on the review-cart view?

**Comment by witekdev** [comment]
That sounds good too.

**Comment by witekdev** [comment]
Fixed

**Comment by witekdev** [comment]
Fixes to https://github.com/jazkarta/jazkarta.shop/issues/29 undid this. reopening

**Comment by witekdev** [comment]
Fixed  on p4_sim_integration branch
