### ISSUE TITLE
Prevent page shifting when first product is added to a cart

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#25]
See https://github.com/jazkarta/sdhsp-buildout/issues/24

**Comment by witekdev** [comment]
@davisagli Not sure if this is something specific to this product or if we should let each site take responsibility for correctly styling it on their own?

**Comment by cewing** [comment]
@witekdev I think this is actually something that belongs in individual themes.  The HTML provided by the shop is reasonable.  And fixing it through a theme is fairly straightforward.
