### ISSUE TITLE
Inaccurate "My Cart" status when shopping as an anonymous user.

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#29]
This seems to be a caching issue as I'm able to get expected behavior on my local instance by turning my caching off. Looks like the "My Cart" indicator is cached on some pages and does not correctly indicate the state of the cart. One can test this by clicking around on http://www.sdhspress.com/ adding books and journals to the cart as anonymous user. One should quickly see inconsistencies. 

@davisagli did you have something like this happen with mtneers perhaps? (or does everyone have to be logged in to shop on mtneers, I forget now)

**Comment by davisagli** [comment]
It hasn't come up, but I suspect it is probably an issue for Mountaineers too. We probably need to make the cart indicator load via an ajax request that is served with a `Cache-control: no-cache, no-store` header so that it loads every time even if the page as a whole is cached.

**Comment by witekdev** [comment]
ok, that makes sense. Thanks!

**Comment by witekdev** [comment]
Fixed in P5, needs to be made compatible with P4

**Comment by witekdev** [comment]
Fixed in P4
