### ISSUE TITLE
Using numbers in checkout process are not helpful from a UI perspective

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#4]
While I understand the reasons behind it. I find the following confusing:
"1 Billing address"
"2 Payment Information"
etc.
even though the "1" and "2" are wrapped in a 'step' class, no other styling is applied to them at the moment. 

I propose we use:
"Step 1 - Billing address"
or 
"Billing address"
or something like that. So either make it explicit or not at all?
or fix the styling to differentiate the "1" from the "Billing address"

or is the idea that each user of the package style this part in their own code?

**Comment by davisagli** [comment]
I'm planning to add more styles (nothing fancy), but haven't yet.

**Comment by davisagli** [comment]
Improved default styles in ea5f6fe
