### ISSUE TITLE
UnicodeEncodeError in Module jazkarta.shop.browser.controlpanel, line 64, in _fetch_orders

### ISSUE THREAD

**Issue by fulv** [jazkarta/jazkarta.shop#54]
https://sentry.io/share/issue/67966c75954042bda3f867eac19deec0/

This happens when users type weird characters in the `title` field.

I have a fix, but I am having a bit of trouble pushing back to the repo right now.

**Comment by fulv** [comment]
ERROR: Permission to jazkarta/jazkarta.shop.git denied to fulv.

**Comment by davisagli** [comment]
@fulv you should be able to open a pull request from a branch in your fork of jazkarta.shop

**Comment by skleinfeldt** [comment]
Thanks for the fix @fulv and let me know if you continue to have trouble.
