### ISSUE TITLE
Stripe API version v1 vs v2

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#6]
My stripe account tells me I'm using the latest API: 2016-07-06 (latest)
and according to stripe themselves - the api version gets set the 1st time you use Stripe with your application: https://stripe.com/docs/upgrades

So I just wanted to bring this into awareness that even though we explicitly embed:
`<script type="text/javascript" src="https://js.stripe.com/v1/"></script>`
inside of jazkarta.shop.browser.stripe.py
(note the **v1**)

Stripe themselves embed an iframe following the footer (I suppose as a result of the above script)

```
<iframe name="stripeXDM_default267056_provider" id="stripeXDM_default267056_provider" src="https://js.stripe.com/v2/channel.html?stripe_xdm_e=http%3A%2F%2Flocalhost%3A8081&amp;stripe_xdm_c=default267056&amp;stripe_xdm_p=1#__stripe_transport__" frameborder="0" style="position: absolute; top: -2000px; left: 0px;"></iframe>
```

(note the **v2**)

So perhaps we should just point directly to Api V2 in jazkarta.shop.browser.stripe.py ?
I just don't know what other repercussions that may have elsewhere in the code, if any.

**Comment by davisagli** [comment]
According to https://groups.google.com/a/lists.stripe.com/forum/#!topic/api-discuss/znXmZ6Duyfw the v1 URL actually returns the same script as the v2 URL, so this should be fine. I updated it.
