### ISSUE TITLE
Error: Couldn't find a distribution for 'jazkarta.shop' (Plone 5.2.2)

### ISSUE THREAD

**Issue by registroforzado** [jazkarta/jazkarta.shop#63]
Hello,

How can I install jazkarta.shop in Plone 5.2.2?

After add it into buildout.cfg and execute bin/buildout, I get:

We have no distributions for jazkarta.shop that satisfies 'jazkarta.shop'.
Couldn't find index page for 'jazkarta.shop' (maybe misspelled?)
Getting distribution for 'jazkarta.shop'.
Couldn't find index page for 'jazkarta.shop' (maybe misspelled?)
While:
  Installing client1.
  Getting distribution for 'jazkarta.shop'.
Error: Couldn't find a distribution for 'jazkarta.shop'.

Thanks

**Comment by cguardia** [comment]
Hi, sorry for the late response. We added installation instructions to the README.
