### ISSUE TITLE
Versions to install in Plone 4 and Plone 5?

### ISSUE THREAD

**Issue by registroforzado** [jazkarta/jazkarta.shop#65]
Hello,

I'm trying to install jazkarta.shop, but I only get errors.

Could you please indicate with which specific versions of Python and Plone the different versions of jazkarta.shop (v2020.1, v2020.2 and master) should be installed?

Thanks

**Comment by cguardia** [comment]
Sorry for the late response. For now, you should run it from master. We just added buildout installation instructions to the README.

**Comment by spanish** [comment]
Current jazkarta.shop Master installed and working with Plone 4.3.10:

[versions]
lxml = 4.0.0
premailer = 3.6.2
cachetools = 3.1.1

I also had to add the following line:
\<include package="z3c.caching" file="meta.zcml" />
to the following file:
/path-to-plone4310/zeocluster/src/jazkarta.shop/jazkarta/shop/browser/configure.zcml

Another day I will try with Plone 5.

Thanks!

PS: I'm registroforzado
