### ISSUE TITLE
after a failed checkout transaction, am unable to follow up with a successful transaction from the same cart

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#7]
In the /checkout view, when submitting a payment for a cart with a test card that will decline (4000000000000002) the checkout view acts appropriately and gives the user an error message.

However when I then follow up with a submit (click the complete purchase button) with a test card that should result in a successful transaction (4000000000000077), it does not work.
In the console I get a:
(index):3 POST https://api.stripe.com/v1/tokens 402 (Payment Required)

This card: 4000000000000077 does otherwise work when I start with a 'freshly' loaded checkout view.

As a reference:
https://stripe.com/docs/testing

**Comment by davisagli** [comment]
I haven't been able to reproduce this one.

**Comment by witekdev** [comment]
ok, I will investigate it again with all the recent fixes in place.

**Comment by witekdev** [comment]
Ok it was a PEBKAC error on my part.
However what I discovered in the process, was that when I was entering the 4000000000000077 (good card) following the 4000000000000002 (bad card) attempt, I was also entering an expiry date of January **2016** and it was silently failing without me knowing, only giving a JS error in the log: 402 (Payment Required).
So that could be a usability improvement to prevent expiry dates that are past the current date?

**Comment by davisagli** [comment]
It's supposed to catch that kind of error and display a message, so I'll take a look.

David Glick
(mobile)

**Comment by davisagli** [comment]
It was displaying the message, but at the top of the form and without error styles, so it was super easy to miss. Fixed.
