### ISSUE TITLE
when product not yet installed - one can add IProduct behavior and see the schema fields 

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#8]
If the IProduct behavior is added to a content type, those schema fields show up in the view of that content type, even though the jazkarta.shop product is not installed.

Not sure if this is just how dexterity does things or if it's an issue?

**Comment by davisagli** [comment]
It's not great that the behavior shows up when the product isn't installed, but I'm not sure there's an easy way to prevent that.

**Comment by alecpm** [comment]
There's currently no way to restrict a behavior registration to a specific layer or make the behavior registration conditional on the product being installed in the ZMI, so I think this is #wontfix.
