### ISSUE TITLE
shipping form - no buttons show up to continue with the checkout process

### ISSUE THREAD

**Issue by witekdev** [jazkarta/jazkarta.shop#9]
![screenshot from 2016-07-08 09 05 56](https://cloud.githubusercontent.com/assets/883619/16693751/84566872-44eb-11e6-89d3-e953375f9ac6.png)

I see no errors in the console either.

**Comment by davisagli** [comment]
Have you configured shipping methods?

(Also, looks like you don't have my new styles.)

**Comment by witekdev** [comment]
I didnt but I now have a shipping method yet I still see this.
Also the **Shipping Fee by Weight**  datagridfield is actually not being validated as required on the Edit Shipping Method view. (not related but btw)

Will investigate the styles

**Comment by davisagli** [comment]
How is the shipping method configured?

**Comment by witekdev** [comment]
you are right, sorry, I had it set for Canada while using a US address. I get a proceed to payment button now.

**Comment by davisagli** [comment]
Maybe we should show a different message if you entered an address but there are no matching shipping methods.

**Comment by witekdev** [comment]
I think it makes sense to show something like that, yes.

**Comment by witekdev** [comment]
Added a "We are currently unable to ship to this address." status message if the address entered is not supported by the existing shipping methods. This is based on the state/country selected.
This shows up once all the required shipping fields have been provided.

We do not check that the zip and state field match. So there is still a way for the user to move forward if they enter a valid zip for any state and then enter a state that is in the allowed list, in the case where the state that would match the entered zip is "disallowed".
